# Generated by Django 5.1.1 on 2024-11-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0006_alter_academicinformation_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
