# Generated by Django 5.1.1 on 2024-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_publicacion', '0004_alter_publicacion_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='multimedia',
            field=models.TextField(),
        ),
    ]
